services:

  mysql:
    image: mysql:8.4

    container_name: sales_mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - sales-network

  api:

    build:
      context: .
      dockerfile: docker/api/Dockerfile

    container_name: sales_api

    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    env_file:
      - .env

    ports:
      - "8000:8000"

    volumes:
      - .:/app
      - ./storage:/app/storage

    working_dir: /app

    networks:
      - sales-network


networks:
  sales-network:


volumes:
  mysql_data: