"""Initial schema

Revision ID: c3247789c958
Revises: 
Create Date: 2026-07-24 20:34:37.949902

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = "c3247789c958"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archivos',
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('nombre_storage', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('extension', sa.String(length=10), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('total_registros', sa.Integer(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='importstatus'), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archivos_file_hash'), 'archivos', ['file_hash'], unique=True)
    op.create_table('ventas',
    sa.Column('archivo_id', sa.Integer(), nullable=False),
    sa.Column('business_key', sa.String(length=64), nullable=False),
    sa.Column('frog_id', sa.String(length=150), nullable=False),
    sa.Column('factura', sa.String(length=100), nullable=True),
    sa.Column('cliente', sa.String(length=255), nullable=True),
    sa.Column('fecha_liquidacion', sa.Date(), nullable=True),
    sa.Column('fabricante', sa.String(length=150), nullable=True),
    sa.Column('preventa', sa.String(length=150), nullable=True),
    sa.Column('reparto', sa.String(length=150), nullable=True),
    sa.Column('denominacion_comercial', sa.String(length=255), nullable=True),
    sa.Column('producto', sa.String(length=255), nullable=True),
    sa.Column('descripcion_canal', sa.String(length=150), nullable=True),
    sa.Column('marca', sa.String(length=150), nullable=True),
    sa.Column('presentacion', sa.String(length=150), nullable=True),
    sa.Column('cajas', sa.DECIMAL(precision=18, scale=4), nullable=True),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('multiplo', sa.DECIMAL(precision=18, scale=4), nullable=True),
    sa.Column('importe_bruto', sa.DECIMAL(precision=18, scale=4), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=18, scale=4), nullable=True),
    sa.Column('factor_conversion_1', sa.DECIMAL(precision=18, scale=4), nullable=True),
    sa.Column('factor_conversion_3', sa.DECIMAL(precision=18, scale=4), nullable=True),
    sa.Column('hlt', sa.DECIMAL(precision=18, scale=4), nullable=True),
    sa.Column('descripcion_producto', sa.String(length=255), nullable=True),
    sa.Column('plaza', sa.String(length=100), nullable=True),
    sa.Column('canal', sa.String(length=100), nullable=True),
    sa.Column('clasificacion', sa.String(length=100), nullable=True),
    sa.Column('cf', sa.String(length=50), nullable=True),
    sa.Column('sabor', sa.String(length=100), nullable=True),
    sa.Column('compania', sa.String(length=150), nullable=True),
    sa.Column('anio', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['archivo_id'], ['archivos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_archivo_id'), 'ventas', ['archivo_id'], unique=False)
    op.create_index(op.f('ix_ventas_business_key'), 'ventas', ['business_key'], unique=True)
    op.create_index(op.f('ix_ventas_frog_id'), 'ventas', ['frog_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ventas_frog_id'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_business_key'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_archivo_id'), table_name='ventas')
    op.drop_table('ventas')
    op.drop_index(op.f('ix_archivos_file_hash'), table_name='archivos')
    op.drop_table('archivos')
    # ### end Alembic commands ###